### ISSUE TITLE
source is missing after app is dormant

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#137]
After leaving ts dormant for a while (a day), when I opened it up again the source was blank and so were the project, chapter, and frame tabs.

I'm not sure if this is reproducible.

**Comment by jag3773** [comment]
Yes, just happened again.
![screenshot_2015-01-06-11-05-29](https://cloud.githubusercontent.com/assets/107731/5633543/c00963f8-9595-11e4-8cf6-7d8c7605808e.png)

**Comment by neutrinog** [comment]
are you able to provide steps to reproduce?

**Comment by jag3773** [comment]
Not exactly.  Something to the effect of go to a frame in the app, then minimize the app, then let the device go to sleep.  Do whatever else you may with your device, then at some point come back and open the app back up, the projects window slides out blank like the above screenshot.

**Comment by jag3773** [comment]
Happened on my s5 now, too.
![screenshot_2015-01-06-18-51-38](https://cloud.githubusercontent.com/assets/107731/5639536/800e81d0-95d5-11e4-8ded-2012cacc70f0.png)
