### ISSUE TITLE
starting up the program after...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#141]
Notes
======
starting up the program after inatalling 2.0.0beta3 tk apk

Environment
======
version: 2.0.2
build: 46
UDID: e7848e883731e8e0
Android Release: 4.1.2
Androind SDK: 16
Brand: verizon
Device: ADR930L
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.ProjectManager.downloadNewProjects(ProjectManager.java:84)
	at com.door43.translationstudio.MainActivity$18.run(MainActivity.java:1408)

**Comment by neutrinog** [comment]
testing release reference in issues.
https://github.com/Door43/translationStudio2/releases/tag/2.0.2

**Comment by neutrinog** [comment]
da31b96

**Comment by neutrinog** [comment]
This has been fixed by initializing the data store in the constructor.
