### ISSUE TITLE
this from the irulu tablet

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#180]
Notes
======
this from the irulu tablet

Environment
======
version: 2.0.3
build: 51
UDID: 36f1a43c66beac04
Android Release: 4.4.2
Androind SDK: 19
Brand: alps
Device: t10

**Comment by neutrinog** [comment]
Screenshot in https://github.com/Door43/translationStudio2/issues/179

Mark Hancock determined this issue is due to the fonts being used. We'll identify which fonts are working and which are not.

**Comment by neutrinog** [comment]
Layout was broken while using Gentium Plus, but worked with Lanna Alif.

**Comment by neutrinog** [comment]
The solution to this bug is to change the font.
Users can change the font from the settings menu.
