### ISSUE TITLE
application is not crashing b...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#202]
Notes
======
application is not crashing but on the samsung galaxy(SM-T530NU) the english is can type but the typeset for other keyboards will not display.  The settings for ts (general,upload,sharing,advanced)is blank.   Mark Hancock has picture for details.

Environment
======
version: 2.0.3
build: 51
UDID: 3ff180e14bf4ee44
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: matissewifiue
Log history
======
1/28/15 11:06 AM [com.door43.translationstudio.projects.data.DataStore]:clearing the asset cache to support api version 2

**Comment by neutrinog** [comment]
This is related to https://github.com/Door43/translationStudio2/issues/164
Seems this is not just an emulator issue.
