### ISSUE TITLE
Just installed app on new Len...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#210]
Notes
======
Just installed app on new Lenovo Tab 2 A7-10. 
android 4.4.2
4core 1.3 GHz
1 GB ram

source frame text does not display or scroll correctly.

looks something like this

t
h
I
s
is how everythi

thanks

Marv Lucas
marv_Lucas@wycliffeassociates.org

Environment
======
version: 2.0.3
build: 51
UDID: 50ff087ff588ad3c
Android Release: 4.4.2
Androind SDK: 19
Brand: Lenovo
Device: Tab2A7-10F

**Comment by neutrinog** [comment]
this is a duplicate https://github.com/Door43/translationStudio2/issues/180
