### ISSUE TITLE
Add Contact Form to Publish

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#223]
When the user selects the the publish toggle on their upload then we also want to provide a simple form for them to fill out that includes:
Name
Email
Phone (optional)

This form should be emailed to us, perhaps via a hook or script on the server?

**Comment by neutrinog** [comment]
What do you think about placing that info in the commit message? or perhaps in the "READY" file in the repo? That way we don't have to worry about security since git already operates via ssh.

**Comment by neutrinog** [comment]
a hook on the server can do the rest.

**Comment by jag3773** [comment]
Yep, that is what I was thinking.  Probably putting it in the READY file would be good.

**Comment by neutrinog** [comment]
I've been thinking about this some more. What if we place a ".profile" directory in the repo instead. This would provide greater flexibility for what user information we want to store. For example we may want to allow users to provide a profile image, or we may want to allow users to sign their own content (similar to our signing identities but only visible on the translation side). e.g. They log into the app through which signing keys are generated from the combination of their username and password.

**Comment by jag3773** [comment]
Great idea.
