### ISSUE TITLE
Bible navigation

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#232]
We need icons or we need to enlarge and center the text for Bible navigation.

Also, I think we should have NT and OT at the top level, perhaps "Bible: New Testament".

**Comment by neutrinog** [comment]
Feel free to update the api to reflect the preferred navigation levels.
e.g. update the meta [bible, nt] and the subsequent translations in the languages catalog.

**Comment by neutrinog** [comment]
updated the lists to center and enlarge the title if no image is present

**Comment by jag3773** [comment]
I've updated the meta section.
