### ISSUE TITLE
no choice for Bible in librar...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#260]
Notes
======
no choice for Bible in libraries

Environment
======
version: 2.0.3
build: 55
UDID: 345d81bb2e44e64a
Android Release: 5.0.2
Androind SDK: 21
Brand: google
Device: grouper
Log history
======
2/6/15 12:06 PM [com.door43.translationstudio.projects.data.DataStore]:clearing the asset cache to support api version 2.2

**Comment by neutrinog** [comment]
the projects just be downloaded first
