### ISSUE TITLE
the profile repo needs to be pushed whenever a project is pushed

### ISSUE THREAD

**Issue by neutrinog** [Door43/translationStudio2#279]

**Comment by neutrinog** [comment]
The app is now pushing the profile to gitolite3@ts.door43.org:tS/<UDID>/profile
The server has yet to be configured to accept this.

**Comment by neutrinog** [comment]
@jag3773 could you please update the server to receive the profiles?

**Comment by jag3773** [comment]
@neutrinog Please test it out.

**Comment by neutrinog** [comment]
oh totally forgot to test this I tried just now but not working. see https://github.com/Door43/translationStudio2/issues/307
I pushed to gitolite3@ts.door43.org:tS/c16d19f40cbe170e/profile

**Comment by jag3773** [comment]
Fixed.
