### ISSUE TITLE
USX Code In Text

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#289]
If you update from the server and then look at Jude you'll see a bunch of USFM code within the source text.

**Comment by jag3773** [comment]
I mean USX.

**Comment by neutrinog** [comment]
moving this over to you so you remember :)
most of it looks like section headings. I've also seen this popping up in other books as well (2 Timothy for example).

**Comment by jag3773** [comment]
Moving back to you so that we get unused code hidden ;)
