### ISSUE TITLE
Record Source Language for Each Project

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#290]
We need to include the source language that each project is configured to translation from.  I think we could put this in a separate "source" file in the git repo and do a commit every time it is changed.  That way we can look back in the log if we need to see other source values than the most recent one.

**Comment by neutrinog** [comment]
ok I'm going to save the source language in a file named "manifest.json". We can store additional information in this file later if necessary.

**Comment by neutrinog** [comment]
here's a sample of the output.
```
{
  "source_language": {
    "resource": {
      "date_modified": 20150129,
      "slug": "obs"
    },
    "date_modified": 20150129,
    "slug": "pt-br"
  }
}
```
