### ISSUE TITLE
Rotating Device Resets Source Text Position

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#291]
If I change from portrait to landscape view (i.e. turn my phone sideways) while I'm reading the text, I am automatically repositioned to the top of the passage that I'm reading. It's a little annoying because then I have to scroll down to find where I was.

**Comment by neutrinog** [comment]
This has been fixed in my device. What device are you using?

**Comment by neutrinog** [comment]
There still is an issue with the notes not maintaining the scroll position, but that is the result of a different problem.

**Comment by neutrinog** [comment]
This might be related to this. https://github.com/Door43/translationStudio2/issues/430

**Comment by jag3773** [comment]
This is on a S5.
