### ISSUE TITLE
Default to ULB

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#292]
On first opening a Bible project the app should default to showing the ULB text, not UDB.

**Comment by neutrinog** [comment]
for the resources we could probably add a sort field to the catalog as well

**Comment by jag3773** [comment]
Note that I'm talking about which one shows up first in the source pane.  Is that what you are referring to also?

**Comment by neutrinog** [comment]
yes, I just figured sorting rather than specifying a default would be more dynamic for future projects.

**Comment by neutrinog** [comment]
so are you ok with adding a sort key to the resources?

**Comment by neutrinog** [comment]
hard code everything!!!
