### ISSUE TITLE
Add a sort key to the project catalog

### ISSUE THREAD

**Issue by neutrinog** [Door43/translationStudio2#293]
The projects are not sorted correctly, This is especially apparent with books of the Bible.
if we add some field "sort":<int> to each project in the projects catalog https://api.unfoldingword.org/ts/txt/2/catalog.json we could properly sort them.

The sorting should be grouped by meta since meta will categorize projects.
For example everything in "bible-nt" will be sorted 1-n and everything in "bible-ot" will be sorted 1-n.

**Comment by jag3773** [comment]
A sort key has been added.
