### ISSUE TITLE
Source Language Picker

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#311]
We need to provide some means of narrowing what source resources are downloaded from the server.  I'm thinking that we should provide a searchable list of languages that would allow someone to choose multiple source languages.  Somewhat similar to the current source language chooser for a project, but this would be selecting languages that the user can read from.  Once we have this information then the app should only download source projects in the selected languages.

**Comment by neutrinog** [comment]
Agreed. I sorta have this half implemented. I want to take the first part of the p2p sharing (where you select the project and language(s)) and make it a little more abstract so I can use it for any importing whether it be from the server, a peer, or a file.

**Comment by neutrinog** [comment]
also, I can't remember if I mentioned this to you but I think placing the download link directly in the projects lists would be way easier for users.
So the first item in the project list will always be a button that says "find more projects" or something. From there we can have options for importing from the server, a peer, or a file.

**Comment by neutrinog** [comment]
I just read this again and realized I totally missed what you said lol. Got it now :)
