### ISSUE TITLE
Translation notes - bold notes are listed twice

### ISSUE THREAD

**Issue by melvilje** [Door43/translationStudio2#320]
Android version 5.0.2 on Nexus 7
OT - Ruth - Chapter 1 - Frame 1 of 9
Translation Notes - the bold words are listed twice
Important Terms - could they be in a list format?  The KT of name does not apply to this passage yet it is listed as a KT. Missing of the KTs are Ephratihite, judge, & Moab

**Comment by neutrinog** [comment]
@jag3773 this originates in the api. This occurs in some of the notes but not in others.
e.g. luk:en:ulb:24-50

```
{
    "id": "24-50",
    "tn": [
      {
        "ref": "It happened",
        "text": "<b>It happened</b>  - \"It came about\""
      },
      {
        "ref": "while he was blessing them",
        "text": "\"While Jesus was asking God to do good to them\""
      },
      {
        "ref": "was carried",
        "text": "<b>was carried</b>  - Since Luke does not specify who <b>carried</b> Jesus up, we don't know if it was God himself or one or more angels. If your language has to specify who did the carrying, it would be best to go with the UDB \"went.\""
      }
    ]
  }
```

**Comment by neutrinog** [comment]
assigning this to you Jesse so you can take a look at it.

**Comment by jag3773** [comment]
@neutrinog Is it ok if we have notes with an empty "ref" field?  Sounds like there are several comments that are being written that do not specific reference any particular text in the passage.

**Comment by neutrinog** [comment]
yes the ref optional but it should at least exists as an empty string.

**Comment by jag3773** [comment]
The API is updated, but the issue remains @neutrinog : search for in 'out of favortism' in https://api.unfoldingword.org/ts/txt/2/1ti/en/notes.json?date_modified=20150225.

**Comment by neutrinog** [comment]
I couldn't find that phrase.
Also, the date_modified on the related resources catalog hasn't been updated (nor has the languages or projects catalogs), so the app would not see the changes.

date_modified should **always** propagate up the api hierarchy.

**Comment by neutrinog** [comment]
I've confirmed this is working now.
