### ISSUE TITLE
When there are no Important Terms for a frame - resources do not show in menu

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/translationStudio2#328]
Genesis 5 has 4 pages with Translation Notes but without Important Words - https://door43.org/en/bible/notes/gen/05/06, https://door43.org/en/bible/notes/gen/05/09, https://door43.org/en/bible/notes/gen/05/12, and https://door43.org/en/bible/notes/gen/05/15. 
On these frames in the APP the menu choice of 'Resources' is not available.
This needs to be corrected.

**Comment by neutrinog** [comment]
That version of the notes is not available in the api at this moment. 
see https://api.unfoldingword.org/ts/txt/2/gen/en/notes.json?date_modified=20150216
There are only notes up to chapter 4.
