### ISSUE TITLE
Integrate Checking Questions

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#358]
Requires #357.

This should probably be another item in the resources pane.

**Comment by neutrinog** [comment]
will we have anything like this for the translation notes?

**Comment by neutrinog** [comment]
just some notes:

translators are required to click on each question before publishing. When they click on a question it will gain a green check mark and will expand to show the answer along with links to related references. The references will be clickable to show a read only popup for the frame.

When published the date modified value from the checking questions api will be recorded in the repo meta so we can track which version of the checking questions were used.

**Comment by neutrinog** [comment]
did all the grunt work, now just need to make it look pretty.

**Comment by neutrinog** [comment]
@jag3773 I don't know if we'll actually have a set of checking questions for each resource or just one for each translation, so for now I'm just grabbing the first list I find in the source language's resources.

**Comment by neutrinog** [comment]
need to place the checking question date_modified stamp in the manifest of the pushed project
