### ISSUE TITLE
After uploading a translation...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#361]
Notes
======
After uploading a translation the app said "nothing to push" after displaying the success dialog

Environment
======
version: 2.1.2
build: 68
UDID: f668cbd24ac3903
Android Release: 4.4.2
Androind SDK: 19
Brand: Lenovo
Device: YT2
Log history
======
2/27/15 2:42 AM  E/com.door43.translationstudio.user.ProfileManager: failed to push the profile to the server
2/27/15 2:42 AM  E/com.door43.translationstudio.user.ProfileManager: failed to push the profile to the server
2/27/15 2:42 AM  I/com.door43.translationstudio.translations.TranslationManager: Publishing project obs to the server
2/27/15 2:41 AM  E/com.door43.translationstudio.user.ProfileManager: failed to load the profile details
java.io.FileNotFoundException: File '/data/user/10/com.translationstudio.androidapp/files/git/profile/contact.json' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:254)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1641)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1659)
	at com.door43.translationstudio.user.ProfileManager.getProfile(ProfileManager.java:34)
	at com.door43.translationstudio.uploadwizard.UploadWizardActivity.startUpload(UploadWizardActivity.java:58)
	at com.door43.translationstudio.uploadwizard.UploadWizardActivity.loadNextFragment(UploadWizardActivity.java:46)
	at com.door43.translationstudio.uploadwizard.UploadWizardActivity.onContinue(UploadWizardActivity.java:105)
	at com.door43.translationstudio.uploadwizard.WizardFragment.onContinue(WizardFragment.java:13)
	at com.door43.translationstudio.uploadwizard.ReviewFragment$2$2.onClick(ReviewFragment.java:71)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:175)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)

2/27/15 2:41 AM  E/com.door43.translationstudio.user.ProfileManager: failed to push the profile to the server
2/27/15 2:41 AM  E/com.door43.translationstudio.MainApplication: non-critical exception
org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at com.door43.translationstudio.git.tasks.repo.PushTask.pushRepo(PushTask.java:96)
	at com.door43.translationstudio.git.tasks.repo.PushTask.doInBackground(PushTask.java:38)
	at com.door43.translationstudio.git.tasks.repo.PushTask.doInBackground(PushTask.java:21)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1174)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 9 more

2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/tit/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/tit/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rut/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rut/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rev/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rev/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/phm/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/phm/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/luk/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/luk/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jud/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jud/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jas/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jas/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/gen/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/gen/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/act/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/act/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2ti/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2ti/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1ti/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1ti/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/ru/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/fr/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/es/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/catalog.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/zep/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/zec/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/tit/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/tit/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/tit/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/tit/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/tit/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/sng/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rut/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rut/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rut/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rut/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rut/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rom/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rev/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rev/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rev/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rev/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/rev/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/pro/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/php/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/phm/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/phm/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/phm/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/phm/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/phm/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/oba/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/num/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/neh/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/nam/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/mrk/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/mic/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/mat/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/mal/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/luk/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/luk/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/luk/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/luk/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/luk/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/lev/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/lam/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jud/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jud/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jud/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jud/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jud/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jos/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jon/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jol/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/job/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jhn/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jer/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jdg/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jas/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jas/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jas/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jas/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/jas/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/hos/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/heb/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/hag/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/hab/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gen/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gen/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gen/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gen/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gen/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/gal/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/ezr/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/ezk/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/exo/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/est/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/eph/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/ecc/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/deu/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/dan/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/col/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/amo/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/act/en/ulb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/act/en/udb/source.json?date_modified=20150219
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/act/en/notes.json?date_modified=20150225
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/act/en/resources.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/act/languages.json
2/27/15 2:39 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/3jn/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ti/en/ulb/source.json?date_modified=20150219
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ti/en/udb/source.json?date_modified=20150219
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ti/en/notes.json?date_modified=20150225
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ti/en/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ti/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2th/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2sa/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2pe/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ki/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2jn/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2co/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/2ch/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ti/en/ulb/source.json?date_modified=20150219
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ti/en/udb/source.json?date_modified=20150219
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/bible/en/terms.json?date_modified=20150225
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ti/en/notes.json?date_modified=20150225
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ti/en/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ti/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1th/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1sa/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1pe/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ki/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1jn/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1co/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/1ch/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/obs/txt/1/am/obs-am.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: The packaged asset does not exist sourceTranslations/obs/am/obs/terms.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/obs/txt/1/am/kt-am.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: The packaged asset does not exist sourceTranslations/obs/am/obs/notes.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/obs/txt/1/am/tN-am.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/obs/am/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/obs/ru/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/obs/fr/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/obs/es/resources.json
2/27/15 2:38 AM  I/com.door43.translationstudio.projects.data.DataStore: downloaded new asset from https://api.unfoldingword.org/ts/txt/2/obs/languages.json
2/27/15 2:38 AM  I/com.door43.translationstudio.MainActivity$26: downloading updates
2/27/15 2:37 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.6

**Comment by neutrinog** [comment]
This was due to the profile repo getting pushed when it was empty.
