### ISSUE TITLE
update the locale

### ISSUE THREAD

**Issue by neutrinog** [Door43/translationStudio2#368]
There have been a number of changes and additions to the wording in the app.
These all need to be translated and the app locale updated.

**Comment by neutrinog** [comment]
The locale is being translated at https://crowdin.com/project/translation-studio

We need someone to go through the app and review all the wording. 
You can also look at all the raw wording (e.g. strings) in the string files located in https://github.com/Door43/translationStudio2/tree/master/app/src/main/res/values.

**Comment by neutrinog** [comment]
I've just uploaded all the latest strings to crowdin.

**Comment by leok22** [comment]
Put all recommendations in a google doc spreadsheet and shared it with Jesse and Joel.

**Comment by neutrinog** [comment]
@leok22 thanks. Could you include the string slugs in that spreadsheet? e.g. Project(s) is title_projects.
That will make it easier to look up and review your suggestions in the context of the app.

**Comment by leok22** [comment]
@neutrinog yes, I added the string slugs. Let me know if you need anything else.

**Comment by leok22** [comment]
https://docs.google.com/spreadsheets/d/1XqF3maCm7c-6U64uNijWf5XOIRjzOhk10DE8SOhzPQE/edit?usp=sharing

That's the link for the doc I made @neutrinog

**Comment by neutrinog** [comment]
The local has been updated. I left a few languages as incomplete so we can get some more feedback before paying to have those translated. I don't think anyone in those languages are using the app just yet anyway. Correct me if wrong.

Incomplete languages are: Amharic, Dari, Pashto, and Tagalog.

**Comment by jag3773** [comment]
Amharic needs to be completed.

**Comment by neutrinog** [comment]
this is done except for a few minor additions I'll have translated once the app is reviewed.

**Comment by neutrinog** [comment]
The last of the locale updates are scheduled for translation.
