### ISSUE TITLE
After updating to 2.1.3 - still see Arabic of most book names

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/translationStudio2#370]
The project's source language is English. 
When I went into another book (in Arabic) my only choice for source language was Arabic.

BTW - tried to submit a bug report but my tK was not working.

**Comment by neutrinog** [comment]
Many of the projects are currently only available in Arabic. Once new source languages are available you'll be able to see them after updating from the menu.

If you are having trouble with tK please open an issue here https://github.com/Door43/translationKeyboard/issues so the developers can address it.
