### ISSUE TITLE
trying to go to Acts 8:37

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#393]
Notes
======
trying to go to Acts 8:37

Environment
======
version: 2.1.3
build: 69
UDID: 345d81bb2e44e64a
Android Release: 5.0.2
Androind SDK: 21
Brand: google
Device: grouper
Stack trace
======
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.door43.translationstudio.spannables.NoteSpan.setOnClickListener(com.door43.translationstudio.spannables.Span$OnClickListener)' on a null object reference
	at com.door43.translationstudio.rendering.USXRenderer.renderNote(USXRenderer.java:154)
	at com.door43.translationstudio.rendering.USXRenderer.render(USXRenderer.java:58)

-- EDIT (joel): Truncated the stacktrace	because it was not helpful

Log history
======

-- EDIT (joel): Truncated the log because it was not helpful.

**Comment by ChrisJarka** [comment]
And now tS will not stay open - it constantly crashes. I tap on tS icon - it asks me to submit a crash report - I cancel - it refreshes - shows empty source text and edit screen - crashes. I cannot change off of the page. Even if I close all 'open' APPs.

**Comment by neutrinog** [comment]
@jag3773  this is a snippet from the Acts 8:36 frame:

```
<note caller="+" style="f">
  Some ancient authorities add, in whole or in part, v. 37.

  <char style="fqa">
    And Philip said, "If you believe with all your heart, you may be baptized." And the Ethiopian answered, I believe that Jesus Christ
  </char>

  is the Son of God.
</note>
```

Notice the note is **not** valid xml.

It should be something like this:

```
<note caller="+" style="f">
  <char style="ft">Some ancient authorities add, in whole or in part, v. 37.</char>
  <char style="fqa">
    And Philip said, "If you believe with all your heart, you may be baptized." And the Ethiopian answered, I believe that Jesus Christ
  </char>
  <char style="ft"> is the Son of God.</char>
</note>
```
