### ISSUE TITLE
scrolled down in Acts 8 frame...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#394]
Notes
======
scrolled down in Acts 8 frame list

Environment
======
version: 2.1.3
build: 69
UDID: dd19773da22f5f
Android Release: 5.0
Androind SDK: 21
Brand: Verizon
Device: kltevzw
Stack trace
======
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.door43.translationstudio.spannables.NoteSpan.setOnClickListener(com.door43.translationstudio.spannables.Span$OnClickListener)' on a null object reference
	at com.door43.translationstudio.rendering.USXRenderer.renderNote(USXRenderer.java:154)
	at com.door43.translationstudio.rendering.USXRenderer.render(USXRenderer.java:58)
	at com.door43.translationstudio.projects.Frame.getDescription(Frame.java:295)
	at com.door43.translationstudio.dialogs.ModelItemAdapter.getView(ModelItemAdapter.java:121)
	at android.widget.AbsListView.obtainView(AbsListView.java:2842)
	at android.widget.ListView.makeAndAddView(ListView.java:1884)
	at android.widget.ListView.fillDown(ListView.java:713)
	at android.widget.ListView.fillGap(ListView.java:677)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:7026)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:6481)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5837)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Log history
======
3/27/15 10:35 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
3/27/15 10:35 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
3/27/15 10:35 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
3/27/15 10:35 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/catalog.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/zep/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/zec/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/tit/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/sng/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rut/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rom/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/rev/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/pro/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/php/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/phm/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/oba/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/num/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/neh/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/nam/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/mrk/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/mic/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/mat/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/mal/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/luk/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/lev/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/lam/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jud/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jos/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jon/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jol/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/job/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jhn/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jer/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jdg/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/jas/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/hos/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/heb/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/hag/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/hab/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/gen/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/gal/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/ezr/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/ezk/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/exo/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/est/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/eph/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/ecc/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/deu/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/dan/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/col/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/amo/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/act/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/3jn/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2ti/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2th/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2sa/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2pe/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2ki/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2jn/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2co/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/2ch/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1ti/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1th/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1sa/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1pe/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1ki/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1jn/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1co/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/1ch/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/ru/resources.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/fr/resources.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/es/resources.json
3/26/15 3:12 PM  I/com.door43.translationstudio.projects.data.DataStore: downloaded updated asset from https://api.unfoldingword.org/ts/txt/2/obs/languages.json
3/26/15 3:12 PM  I/com.door43.translationstudio.MainActivity$26: downloading updates

**Comment by neutrinog** [comment]
This issue is the same as https://github.com/Door43/translationStudio2/issues/393
