### ISSUE TITLE
Lollypop issue for tS

### ISSUE THREAD

**Issue by markellishancock** [Door43/translationStudio2#396]
Bruce Smith and I are having issues with our Nexus 7  on Android version 5.0.2.  When working on OBS (en) The Creation...We won't have any menus to click update or go back and the blue bar (on the top) will stay on.  When I use my 4.4.2 toshiba tablet...the blue bar will stay blue (with no menu bars) but once I am done editing the bar is green with menus.
![screenshot_2015-03-30-10-50-41](https://cloud.githubusercontent.com/assets/11721717/6902959/2cd8bd0e-d6e5-11e4-9056-4db5c1ff89e5.png)

**Comment by neutrinog** [comment]
duplicate https://github.com/Door43/translationStudio2/issues/312
