### ISSUE TITLE
tN shows under IT heading.

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#406]
Notes
======
tN shows under IT heading.

Environment
======
version: 2.1.4
build: 78
UDID: 9f023fc4659b778f
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: degaswifiue
Log history
======
4/2/15 1:40 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term God the Son
4/2/15 1:39 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term God the Son
4/2/15 11:55 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9

**Comment by jag3773** [comment]
Reproduce by: 1. On OBS frame 1, click on God, the correct IT pops out.  2. Close, navigate to frame 2, click on good, then the tN show up in the resources pane, although the Important Terms heading is highlighted.

This seems consistent, no matter what the frames are that are navigated between.  Perhaps related to #391 .
