### ISSUE TITLE
Notes Issue in Gen 5:6

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#409]
From Christine Jarka:
Genesis 5.9 has a problem with the Translation Notes in Door43 going to tS (even v2.1.4)
The web page note is: The records in Genesis 5:6-27 have the same format. Translate them according to the notes for verse 6-8. 
The app has: 27 have the same format. Translate them according to the notes for verse 6-8.

**Comment by neutrinog** [comment]
@jag3773 You might have already noticed, but this is an api issue. It must have been truncated between the web page and the api.

**Comment by jag3773** [comment]
Fixed.
