### ISSUE TITLE
Back button took me out of th...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#428]
Notes
======
Back button took me out of the app

Environment
======
version: 2.1.5
build: 79
UDID: d8d097ad47b4c1ff
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: degaswifiue
Log history
======
4/9/15 12:15 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:figuresofspeech:doublet
4/9/15 12:15 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:pluralpronouns
4/9/15 12:15 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:figuresofspeech:doublet
4/9/15 12:15 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:pluralpronouns
4/9/15 12:11 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
4/9/15 12:11 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
4/9/15 12:11 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52

**Comment by jag3773** [comment]
I was on Gen. 5:3, I opened the resources, followed the link to 4:25 under "Seth" and then I clicked the back button to get back to Gen 5:3 but the app closed.

**Comment by neutrinog** [comment]
For now I am displaying a confirmation dialog when the user presses the back button.
Using the back button in the way described in the previous comment is covered in issue https://github.com/Door43/translationStudio2/issues/429
