### ISSUE TITLE
Key Terms not in 2.2.0 APK

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#486]
The key terms were not included in the APK it seems.  We need to regenerate the apk.

**Comment by jag3773** [comment]
Specifically for OBS.

**Comment by neutrinog** [comment]
@jag3773 
oh... you know what. I did place the latest source in the apk, but I forgot to bump the internal source version so the cache would be cleared (and use the stuff stored in the apk). Try clearing your app cache manually and see if that works. If so then I'll just need to bump that version number.

**Comment by neutrinog** [comment]
still looking into this. The information is there, but there is a bug in the term rendering. I can probably get this fixed over the weekend a little at a time.
