### ISSUE TITLE
Download OBS Drafts from Server

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#91]
We need a feature that allows someone to download a given translation from door43 to work on.  As an example, if someone knows that Russian is part way done on door43, they should be able to download what is available from door43 and then start working on it.

Since all the repos are on Github, it might make sense to just do a clone of the repo from github, e.g. Russian would be at Door43/d43-ru.  However, server to download from should be configurable in the settings menu.  Pushing their updates would still go the normal route (not directly to github).

**Comment by neutrinog** [comment]
Could you explain a little more how you plan to handle this on the server side?
There could be multiple people pushing Russian translations to the server. Are we downloading these or from the official repo e.g. after using dokuwiki git merge tool.
